#
# ██████╗  ██████╗  ██████╗ ███████╗
# ██╔══██╗██╔═══██╗██╔════╝ ██╔════╝     Roger Gonzalez
# ██████╔╝██║   ██║██║  ███╗███████╗     https://rogs.me
# ██╔══██╗██║   ██║██║   ██║╚════██║
# ██║  ██║╚██████╔╝╚██████╔╝███████║
# ╚═╝  ╚═╝ ╚═════╝  ╚═════╝ ╚══════╝
#
# herdr configuration
# Tangled from README.org
#

onboarding = false

[theme]
name = "catppuccin"

[terminal]
new_cwd = "follow"

[ui]
prompt_new_tab_name = false

[keys]
detach = "prefix+d"
rename_workspace = "prefix+$"
workspace_picker = "prefix+s"
goto = "prefix+g"

new_tab = "prefix+c"
rename_tab = "prefix+comma"
close_tab = "prefix+ampersand"
next_tab = "prefix+n"
previous_tab = "prefix+p"
switch_tab = "prefix+1..9"

split_vertical = "prefix+|"
split_horizontal = "prefix+minus"

focus_pane_left = "prefix+h"
focus_pane_down = "prefix+j"
focus_pane_up = "prefix+k"
focus_pane_right = "prefix+l"

resize_mode = "prefix+shift+r"

close_pane = "prefix+x"
zoom = "prefix+z"

copy_mode = "prefix+["

reload_config = "prefix+r"
