# Defaults: https://github.com/Aider-AI/aider/blob/32faf82b31c54d6f19c5c3d63bc294f748bd3e72/aider/resources/model-settings.yml

# Claude Sonnet 4 — mirrors upstream settings
- name: openai/anthropic/claude-sonnet-4-20250514
  edit_format: diff
  weak_model_name: openai/anthropic/claude-3-5-haiku-20241022
  use_repo_map: true
  extra_params:
    extra_headers:
      anthropic-beta: "prompt-caching-2024-07-31,pdfs-2024-09-25,output-128k-2025-02-19"
    max_tokens: 64000
  cache_control: true
  editor_model_name: openai/anthropic/claude-sonnet-4-20250514
  editor_edit_format: editor-diff
  accepts_settings:
    - thinking_tokens

# Claude 3.5 Haiku — mirrors upstream settings
- name: openai/anthropic/claude-3-5-haiku-20241022
  edit_format: diff
  weak_model_name: anthropic/claude-3-5-haiku-20241022
  use_repo_map: true
  extra_params:
    extra_headers:
      anthropic-beta: prompt-caching-2024-07-31,pdfs-2024-09-25
  cache_control: true

# Gemini 2.5 Flash — mirrors upstream settings
- name: openai/gemini/gemini-2.5-flash
  edit_format: diff-fenced
  weak_model_name: openai/gemini/gemini-2.0-flash
  use_repo_map: true
  overeager: true
  use_temperature: false
  accepts_settings:
    - thinking_tokens

# Gemini 2.0 Flash - mirrors upstream settings
- name: openai/gemini/gemini-2.0-flash
  edit_format: diff
  use_repo_map: true

# Qwen 3 Coder 480B — mirrors upstream defaults
- name: openai/cerebras/qwen-3-coder-480b
  edit_format: diff
  weak_model_name: openai/gemini/gemini-2.0-flash
  use_repo_map: true

# Kimi K2 Instruct — mirrors upstream defaults
- name: openai/groq/moonshotai/kimi-k2-instruct-0905
  edit_format: diff
  weak_model_name: openai/gemini/gemini-2.0-flash
  use_repo_map: true
  examples_as_sys_msg: true
  extra_params:
    temperature: 0.6

# Grok Code Fast — mirrors upstream defaults for Grok 4
- name: openai/xai/grok-code-fast
  use_repo_map: true
  edit_format: diff
  weak_model_name: openai/gemini/gemini-2.0-flash
  accepts_settings:
    - reasoning_effort
