alias:
  # Claude
  - "lazer-sonnet:openai/anthropic/claude-sonnet-4-5"
  - "lazer-haiku:openai/anthropic/claude-3-5-haiku-20241022"
  # Gemini
  - "lazer-gemini-flash:openai/gemini/gemini-2.5-flash"
  - "lazer-gemini-weak:openai/gemini/gemini-2.0-flash"
  # Qwen3
  - "lazer-qwen:openai/cerebras/qwen-3-coder-480b"
  # Kimi K2
  - "lazer-kimi:openai/groq/moonshotai/kimi-k2-instruct-0905"
  # Grok Code Fast
  - "lazer-grok:openai/xai/grok-code-fast-1"

cache-prompts: true
cache-keepalive-pings: 6

dark-mode: true
pretty: true
stream: true
