#!/usr/bin/env python3
"""Generate an offline Slack/Teams copy-ready page from a UTF-8 message file.

Requires Python 3 and Node.js 20+. No package installation or network at runtime.
Content filtering and inferred heading styles are the caller's responsibility.
"""

import argparse
import base64
import hashlib
import html
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile

ASSETS = Path(__file__).resolve().parent.parent / "assets"
SIGNATURE = "<!-- Generated by chat-paste v1. -->"
DEFAULT_OUTPUT_DIR = Path("/tmp")


def script_json(data):
    return (
        json.dumps(data, ensure_ascii=False)
        .replace("&", "\\u0026")
        .replace("<", "\\u003c")
        .replace(">", "\\u003e")
        .replace("\u2028", "\\u2028")
        .replace("\u2029", "\\u2029")
    )


def format_message(text):
    result = subprocess.run(
        ["node", str(ASSETS / "formatter.js")],
        input=json.dumps({"text": text}),
        capture_output=True,
        text=True,
        timeout=15,
        check=False,
    )
    if result.returncode:
        raise ValueError(result.stderr.strip() or "The formatter failed.")
    return json.loads(result.stdout)


def render(
    text, title="Slack and Teams message", destination="both", *, revision_note=""
):
    if destination not in ("slack", "teams", "both"):
        raise ValueError("Destination must be slack, teams, or both.")
    formatted = format_message(text)
    scripts, hashes = [], []
    for name in ("vendor/marked.umd.js", "formatter.js", "preview.js"):
        js = (ASSETS / name).read_text(encoding="utf-8")
        js = re.sub(r"</script", r"<\/script", js, flags=re.I)
        hashes.append(
            "'sha256-"
            + base64.b64encode(hashlib.sha256(js.encode()).digest()).decode()
            + "'"
        )
        scripts.append("<script>" + js + "</script>")
    csp = (
        "default-src 'none'; script-src "
        + " ".join(hashes)
        + "; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"
    )
    replacements = {
        "__CSP__": html.escape(csp, quote=True),
        "__TITLE__": html.escape(title, quote=True),
        "__DATA__": script_json(
            {
                "text": formatted["source"],
                "title": title,
                "destination": destination,
                "revisionNote": revision_note,
            }
        ),
        "__SCRIPTS__": "\n".join(scripts),
    }
    template = (ASSETS / "preview.html").read_text(encoding="utf-8")
    page = re.sub(
        r"__(?:CSP|TITLE|DATA|SCRIPTS)__", lambda m: replacements[m[0]], template
    )
    return page, formatted["warnings"]


def write_preview(page, output, *, legacy_signatures=()):
    """Atomically replace only a generated page; preserve unrelated files."""
    output = Path(output).expanduser()
    if output.suffix.lower() != ".html":
        raise ValueError("The output filename must end in .html.")
    if output.is_symlink():
        raise ValueError("Refusing to overwrite a symlink.")
    if output.exists():
        header = output.read_text(encoding="utf-8")[:200]
        if not any(marker in header for marker in (SIGNATURE, *legacy_signatures)):
            raise ValueError(f"Refusing to overwrite an unrelated file: {output}")
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=output.parent,
            prefix=f".{output.name}.",
            delete=False,
        ) as file:
            temporary = Path(file.name)
            file.write(page)
        os.replace(temporary, output)
    finally:
        if temporary:
            temporary.unlink(missing_ok=True)


def add_browser_arguments(parser):
    """Shared delivery policy for this CLI and workflow adapters."""
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--open",
        dest="open_browser",
        action="store_true",
        help="Open the generated page in the default browser (default)",
    )
    group.add_argument(
        "--no-open",
        dest="open_browser",
        action="store_false",
        help="Generate without opening a browser",
    )
    parser.set_defaults(open_browser=True)


def describe_preview(output, destination, warnings, *, open_browser=True):
    output = Path(output).absolute()
    print(f"Formatted preview: {output}")
    print(f"Open: {output.as_uri()}")
    buttons = (
        "'Copy for Slack' or 'Copy for Teams'"
        if destination == "both"
        else f"'Copy for {destination.title()}'"
    )
    print(f"Use {buttons}, then paste normally in the destination app.")
    for warning in warnings:
        print(f"Formatting note: {warning}")
    if open_browser:
        try:
            subprocess.run(
                ["xdg-open", str(output)],
                timeout=10,
                check=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except (OSError, subprocess.SubprocessError) as error:
            print(
                f"Preview generated, but automatic opening failed: {error}",
                file=sys.stderr,
            )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("file", nargs="?", help="UTF-8 Markdown or plain-text message")
    parser.add_argument(
        "--stdin",
        action="store_true",
        help="Read the message from standard input; requires --output",
    )
    parser.add_argument(
        "--output", help="HTML output path; defaults to /tmp/<source name>.html"
    )
    parser.add_argument(
        "--destination", choices=["slack", "teams", "both"], default="both"
    )
    parser.add_argument("--title", default="Slack and Teams message")
    parser.add_argument(
        "--revision-note",
        default="",
        help="Optional caller-provided note about editing the source",
    )
    parser.add_argument(
        "--owned-marker",
        action="append",
        default=[],
        help="Allow replacing an older generated HTML file with this exact ownership marker",
    )
    add_browser_arguments(parser)
    args = parser.parse_args()
    if bool(args.file) == args.stdin:
        parser.error("Provide a message file or --stdin, but not both.")
    if args.stdin and not args.output:
        parser.error("--stdin requires --output.")
    try:
        source = (
            Path(args.file).expanduser().resolve(strict=True) if args.file else None
        )
        text = source.read_text(encoding="utf-8") if source else sys.stdin.read()
        output = (
            Path(args.output).expanduser().absolute()
            if args.output
            else DEFAULT_OUTPUT_DIR / source.with_suffix(".html").name
        )
        if source and output.resolve() == source:
            raise ValueError("The output must not overwrite the source message.")
        page, warnings = render(
            text, args.title, args.destination, revision_note=args.revision_note
        )
        write_preview(page, output, legacy_signatures=args.owned_marker)
        describe_preview(
            output, args.destination, warnings, open_browser=args.open_browser
        )
    except (OSError, ValueError, subprocess.SubprocessError) as error:
        print(f"Formatting failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
