#!/usr/bin/env python3
"""Prepare an EOD's public body for optional clipboard export.

Without chat-paste, delivery continues as checked plain text. When installed,
the formatter is invoked only through its public stdin/output CLI contract.
"""

import argparse
from pathlib import Path
import re
import subprocess
import sys

CHAT_PASTE_CLI = (
    Path.home() / ".claude" / "skills" / "chat-paste" / "scripts" / "render_message.py"
)
LEGACY_SIGNATURE = "<!-- Generated by EOD formatter v1. -->"


def public_text(text):
    """Remove private log material before it reaches Node, JSON, or the page."""
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    return re.split(
        r"^\s{0,3}#{1,6}\s+Internal notes\b.*$",
        normalized,
        maxsplit=1,
        flags=re.M | re.I,
    )[0].strip()


def prepare_message(text, mode):
    """Apply EOD policy before any content reaches the general formatter."""
    source = public_text(text)
    if re.search(
        r"^\s*(?:Before you send:|Reviewer:|.*Friday reminder:)", source, re.M | re.I
    ):
        raise ValueError(
            "Remove review flags and reminders. Render only the saved message body."
        )
    lines = source.split("\n")
    result = []
    fenced = False
    for index, line in enumerate(lines):
        if re.match(r"^\s*(?:```|~~~)", line):
            fenced = not fenced
            result.append(line)
            continue
        if fenced:
            result.append(line)
            continue
        trimmed = line.strip()
        letters = [
            letter for letter in re.sub(r"@\S+", "", trimmed) if letter.isalpha()
        ]
        caps = len(letters) >= 2 and all(letter.isupper() for letter in letters)
        weekly = (
            mode == "weekly"
            and len(trimmed) <= 100
            and not re.search(r"[.!?:]$", trimmed)
            and not re.match(r"Hey\b", trimmed, re.I)
            and (index == 0 or not lines[index - 1].strip())
            and index + 1 < len(lines)
            and bool(lines[index + 1].strip())
        )
        plain_line = not re.match(r"^\s*(?:[#>*•+\-]|\d+[.)]\s)", line)
        if (
            trimmed
            and plain_line
            and (caps or trimmed.startswith("Weekly Recap") or weekly)
        ):
            line = "## " + trimmed
        result.append(line)
    return "\n".join(result)


def channel(path):
    if not path:
        return "slack"
    raw = Path(path).expanduser().read_text(encoding="utf-8")
    match = re.match(r"^---\s*\n(.*?)\n---", raw, re.S)
    if match:
        field = re.search(r"^channel:\s*(.*)$", match[1], re.M)
        if field and "teams" in field[1].lower():
            return "teams"
    return "slack"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "file", help="Saved final .md draft; output is the matching .html file"
    )
    parser.add_argument(
        "--mode", choices=["client", "internal", "weekly"], default="client"
    )
    parser.add_argument(
        "--client", help="Client config, used only to recommend a copy button"
    )
    browser = parser.add_mutually_exclusive_group()
    browser.add_argument(
        "--open",
        dest="open_browser",
        action="store_true",
        help="Ask the optional formatter to open the preview",
    )
    browser.add_argument(
        "--no-open",
        dest="open_browser",
        action="store_false",
        help="Generate without opening a browser",
    )
    parser.set_defaults(open_browser=None)
    args = parser.parse_args()
    try:
        draft = Path(args.file).expanduser().resolve(strict=True)
        if (
            draft.suffix != ".md"
            or draft.name.endswith(".notes.md")
            or draft.name == "client.md"
        ):
            raise ValueError(
                "Render a final .md message, not raw notes or client configuration."
            )
        output = draft.with_suffix(".html")
        public_message = prepare_message(draft.read_text(encoding="utf-8"), args.mode)
        if not public_message:
            raise ValueError("The public message is empty.")
        if not CHAT_PASTE_CLI.is_file():
            print(
                "Clipboard preview skipped: chat-paste is not installed. Deliver the checked EOD as plain text; no preview was generated."
            )
            return 0
        target = "slack" if args.mode == "internal" else channel(args.client)
        command = [
            sys.executable,
            str(CHAT_PASTE_CLI),
            "--stdin",
            "--output",
            str(output),
            "--title",
            f"EOD: {draft.stem}",
            "--destination",
            target,
            "--owned-marker",
            LEGACY_SIGNATURE,
            "--revision-note",
            "For revisions, update the checked draft and regenerate this page. Only the initial message body has passed the writing checker.",
        ]
        if args.open_browser is not None:
            command.append("--open" if args.open_browser else "--no-open")
        result = subprocess.run(
            command,
            input=public_message,
            text=True,
            capture_output=True,
            timeout=45,
            check=False,
        )
        sys.stdout.write(result.stdout)
        sys.stderr.write(result.stderr)
        return result.returncode
    except (OSError, ValueError, subprocess.SubprocessError) as error:
        print(f"Formatting failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
