#!/usr/bin/env python3
"""Generate a self-contained Slack/Teams clipboard page beside a final EOD draft.

Requires Python 3 and Node.js 20+. Runtime is offline and dependency-free.
The browser page needs Chromium to copy Slack's native clipboard format.
"""

import argparse
import base64
import hashlib
import html
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile

ASSETS = Path(__file__).resolve().parent.parent / "assets"
SIGNATURE = "<!-- Generated by EOD formatter v1. -->"


def public_text(text):
    """Remove private log material before it reaches Node, JSON, or the page."""
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    return re.split(
        r"^\s{0,3}#{1,6}\s+Internal notes\b.*$",
        normalized,
        maxsplit=1,
        flags=re.M | re.I,
    )[0].strip()


def script_json(data):
    return (
        json.dumps(data, ensure_ascii=False)
        .replace("&", "\\u0026")
        .replace("<", "\\u003c")
        .replace(">", "\\u003e")
        .replace("\u2028", "\\u2028")
        .replace("\u2029", "\\u2029")
    )


def format_message(text, mode):
    result = subprocess.run(
        ["node", str(ASSETS / "formatter.js")],
        input=json.dumps({"text": text, "mode": mode}),
        capture_output=True,
        text=True,
        timeout=15,
        check=False,
    )
    if result.returncode:
        raise ValueError(result.stderr.strip() or "The formatter failed.")
    return json.loads(result.stdout)


def render(text, title, mode):
    formatted = format_message(public_text(text), mode)
    scripts = []
    hashes = []
    for name in ("vendor/marked.umd.js", "formatter.js", "preview.js"):
        js = (ASSETS / name).read_text(encoding="utf-8")
        js = re.sub(r"</script", r"<\/script", js, flags=re.I)
        hashes.append(
            "'sha256-"
            + base64.b64encode(hashlib.sha256(js.encode()).digest()).decode()
            + "'"
        )
        scripts.append("<script>" + js + "</script>")
    csp = (
        "default-src 'none'; script-src "
        + " ".join(hashes)
        + "; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"
    )
    replacements = {
        "__CSP__": html.escape(csp, quote=True),
        "__TITLE__": html.escape(title, quote=True),
        "__DATA__": script_json(
            {"text": formatted["source"], "title": title, "mode": mode}
        ),
        "__SCRIPTS__": "\n".join(scripts),
    }
    # Substitute once so message content cannot introduce template replacements.
    template = (ASSETS / "preview.html").read_text(encoding="utf-8")
    page = re.sub(
        r"__(?:CSP|TITLE|DATA|SCRIPTS)__", lambda m: replacements[m[0]], template
    )
    return page, formatted["warnings"]


def channel(path):
    if not path:
        return "slack"
    raw = Path(path).expanduser().read_text(encoding="utf-8")
    match = re.match(r"^---\s*\n(.*?)\n---", raw, re.S)
    if match:
        field = re.search(r"^channel:\s*(.*)$", match[1], re.M)
        if field and "teams" in field[1].lower():
            return "teams"
    return "slack"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "file", help="Saved final .md draft; output is the matching .html file"
    )
    parser.add_argument(
        "--mode", choices=["client", "internal", "weekly", "markdown"], default="client"
    )
    parser.add_argument(
        "--client", help="Client config, used only to recommend a copy button"
    )
    parser.add_argument(
        "--open",
        action="store_true",
        help="Open the generated page in the default browser",
    )
    args = parser.parse_args()
    try:
        draft = Path(args.file).expanduser().resolve(strict=True)
        if (
            draft.suffix != ".md"
            or draft.name.endswith(".notes.md")
            or draft.name == "client.md"
        ):
            raise ValueError(
                "Render a final .md message, not raw notes or client configuration."
            )
        output = draft.with_suffix(".html")
        if output.is_symlink():
            raise ValueError("Refusing to overwrite a symlink.")
        if (
            output.exists()
            and SIGNATURE not in output.read_text(encoding="utf-8")[:200]
        ):
            raise ValueError(f"Refusing to overwrite an unrelated file: {output}")
        target = "slack" if args.mode == "internal" else channel(args.client)
        page, warnings = render(
            draft.read_text(encoding="utf-8"), f"EOD: {draft.stem}", args.mode
        )
        # Create with mode 0600 and replace atomically: a failed write must not
        # leave a partial preview or briefly expose client text with mode 0644.
        temporary = None
        try:
            with tempfile.NamedTemporaryFile(
                mode="w",
                encoding="utf-8",
                dir=output.parent,
                prefix=f".{output.name}.",
                delete=False,
            ) as file:
                temporary = Path(file.name)
                file.write(page)
            os.replace(temporary, output)
        finally:
            if temporary:
                temporary.unlink(missing_ok=True)
        print(f"Formatted preview: {output}")
        print(f"Open: {output.as_uri()}")
        print(
            f"Use 'Copy for {'Teams' if target == 'teams' else 'Slack'}', then paste with Ctrl+V."
        )
        for warning in warnings:
            print(f"Formatting note: {warning}")
        if args.open:
            try:
                subprocess.run(
                    ["xdg-open", str(output)],
                    timeout=10,
                    check=True,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
            except (OSError, subprocess.SubprocessError) as error:
                print(
                    f"Preview generated, but automatic opening failed: {error}",
                    file=sys.stderr,
                )
    except (OSError, ValueError, subprocess.SubprocessError) as error:
        print(f"Formatting failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
